development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: <%= ENV['EMAIL_SENDER'] %>
  :password: <%= ENV['EMAIL_PASSWORD'] %>
  :enable_starttls_auto: true
# production:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: "areawidesender@gmail.com"
#   :password: "Areawide_3"
#   :enable_starttls_auto: true
production:
  :port:            <%= ENV['MAILGUN_SMTP_PORT'] %>
  :address:         <%= ENV['MAILGUN_SMTP_SERVER'] %>
  :user_name:       <%= ENV['MAILGUN_SMTP_LOGIN'] %>
  :password:        <%= ENV['MAILGUN_SMTP_PASSWORD'] %>
  :domain:          "areawide-mobile-api.heroku.com"
  :authentication:  plain
  :enable_starttls_auto: true