development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: <%= ENV['EMAIL_SENDER'] %>
  :password: <%= ENV['EMAIL_PASSWORD'] %>
  :enable_starttls_auto: true
# production:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: "areawidesender@gmail.com"
#   :password: "Areawide_3"
#   :enable_starttls_auto: true
production:
  :port:            587
  :address:         smtp.mailgun.org
  :user_name:       postmaster@sandbox030884ec0bfb437989dab7eae1d29204.mailgun.org
  :password:        73f166d58e03fcc82c577ad61d201655-b6d086a8-87098193
  :domain:          "areawide-mobile-api.heroku.com"
  :authentication:  plain
  :enable_starttls_auto: true